# Generated by Django 4.1.7 on 2023-03-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0004_category_remove_article_price_article_time_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SOS.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
