# Generated by Django 4.1.7 on 2023-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0005_article_category_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Category',
            field=models.CharField(choices=[('mat', 'Maternite'), ('sec', 'Secours'), ('sex', 'Sexualite'), ('div', 'Divers')], max_length=50),
        ),
    ]
