# Generated by Django 4.1.7 on 2023-05-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0007_alter_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='about',
            new_name='description',
        ),
    ]
