# Generated by Django 4.1.7 on 2023-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0008_rename_about_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hopitals',
            name='urlmap',
            field=models.URLField(default=2, max_length=10000),
            preserve_default=False,
        ),
    ]
